In [1]:
cd /content/drive/MyDrive/ColabNotebooks/ML/flood-prediction

/content/drive/MyDrive/ColabNotebooks/ML/flood-prediction


# **Importing the Libraries and reading the data** 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [ ]:
data=pd.read_csv("rainfall.csv")
data
# data.iloc[:10]

SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0     ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5   
1     ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1   
2     ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9   
3     ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1   
4     ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7   
...                         ...   ...   ...    ...   ...    ...    ...    ...   
4111                LAKSHADWEEP  2011   5.1    2.8   3.1   85.9  107.2  153.6   
4112                LAKSHADWEEP  2012  19.2    0.1   1.6   76.8   21.2  327.0   
4113                LAKSHADWEEP  2013  26.2   34.4  37.5    5.3   88.3  426.2   
4114                LAKSHADWEEP  2014  53.2   16.1   4.4   14.9   57.4  244.1   
4115                LAKSHADWEEP  2015   2.2    0.5   3.7   87.1  133.1  296.6   

        JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0     365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3   
1     228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3   
2     728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1   
3     502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9   
4     368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7   
...     ...    ...    ...    ...    ...    ...     ...      ...      ...   
4111  350.2  254.0  255.2  117.4  184.3   14.9  1533.7      7.9    196.2   
4112  231.5  381.2  179.8  145.9   12.4    8.8  1405.5     19.3     99.6   
4113  296.4  154.4  180.0   72.8   78.1   26.7  1426.3     60.6    131.1   
4114  116.1  466.1  132.2  169.2   59.0   62.3  1395.0     69.3     76.7   
4115  257.5  146.4  160.4  165.4  231.0  159.0  1642.9      2.7    223.9   

      Jun-Sep  Oct-Dec  
0      1696.3    980.3  
1      2185.9    716.7  
2      1874.0    690.6  
3      1977.6    571.0  
4      1624.9    630.8  
...       ...      ...  
4111   1013.0    316.6  
4112   1119.5    167.1  
4113   1057.0    177.6  
4114    958.5    290.5  
4115    860.9    555.4  

[4116 rows x 19 columns]

# **Identifying the dependent and independent variables**

In [ ]:
features = data.iloc[:, :]
features = features.drop(["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC", "ANNUAL"], axis="columns")

flood = []
for i in range(0,len(data)):
   if data.iloc[i, 14]>2400:
     flood.append('1')
   else:
     flood.append('0')


data["ANNUAL"] = pd.DataFrame(flood[:])
target = data.iloc[:, 14]

In [ ]:
features

SUBDIVISION  YEAR  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec
0     ANDAMAN & NICOBAR ISLANDS  1901    136.3    560.3   1696.3    980.3
1     ANDAMAN & NICOBAR ISLANDS  1902    159.8    458.3   2185.9    716.7
2     ANDAMAN & NICOBAR ISLANDS  1903    156.7    236.1   1874.0    690.6
3     ANDAMAN & NICOBAR ISLANDS  1904     24.1    506.9   1977.6    571.0
4     ANDAMAN & NICOBAR ISLANDS  1905      1.3    309.7   1624.9    630.8
...                         ...   ...      ...      ...      ...      ...
4111                LAKSHADWEEP  2011      7.9    196.2   1013.0    316.6
4112                LAKSHADWEEP  2012     19.3     99.6   1119.5    167.1
4113                LAKSHADWEEP  2013     60.6    131.1   1057.0    177.6
4114                LAKSHADWEEP  2014     69.3     76.7    958.5    290.5
4115                LAKSHADWEEP  2015      2.7    223.9    860.9    555.4

[4116 rows x 6 columns]

In [ ]:
target

0       1
1       1
2       1
3       1
4       1
       ..
4111    0
4112    0
4113    0
4114    0
4115    0
Name: ANNUAL, Length: 4116, dtype: object

In [ ]:
features.isnull().sum()

SUBDIVISION     0
YEAR            0
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [ ]:
target.isnull().sum()

0

# **Encoding the states**

In [ ]:
set(data.iloc[:, 0])
len(data)
states = enumerate(set(data.iloc[:, 0]))
# states = enumerate(set(data[:, 0]))
states = {v:k for k, v in states}

In [ ]:
states

{'ANDAMAN & NICOBAR ISLANDS': 22,
 'ARUNACHAL PRADESH': 4,
 'ASSAM & MEGHALAYA': 28,
 'BIHAR': 31,
 'CHHATTISGARH': 13,
 'COASTAL ANDHRA PRADESH': 29,
 'COASTAL KARNATAKA': 6,
 'EAST MADHYA PRADESH': 16,
 'EAST RAJASTHAN': 9,
 'EAST UTTAR PRADESH': 19,
 'GANGETIC WEST BENGAL': 20,
 'GUJARAT REGION': 23,
 'HARYANA DELHI & CHANDIGARH': 24,
 'HIMACHAL PRADESH': 15,
 'JAMMU & KASHMIR': 17,
 'JHARKHAND': 33,
 'KERALA': 8,
 'KONKAN & GOA': 26,
 'LAKSHADWEEP': 32,
 'MADHYA MAHARASHTRA': 7,
 'MATATHWADA': 34,
 'NAGA MANI MIZO TRIPURA': 18,
 'NORTH INTERIOR KARNATAKA': 21,
 'ORISSA': 10,
 'PUNJAB': 30,
 'RAYALSEEMA': 0,
 'SAURASHTRA & KUTCH': 12,
 'SOUTH INTERIOR KARNATAKA': 27,
 'SUB HIMALAYAN WEST BENGAL & SIKKIM': 11,
 'TAMIL NADU': 1,
 'TELANGANA': 25,
 'UTTARAKHAND': 35,
 'VIDARBHA': 3,
 'WEST MADHYA PRADESH': 5,
 'WEST RAJASTHAN': 2,
 'WEST UTTAR PRADESH': 14}

In [ ]:
state_codes = []
for i in features.iloc[:, 0]:
    state_codes.append(states[i])
features.iloc[:, 0] = state_codes

In [ ]:
features

SUBDIVISION  YEAR  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec
0              22  1901    136.3    560.3   1696.3    980.3
1              22  1902    159.8    458.3   2185.9    716.7
2              22  1903    156.7    236.1   1874.0    690.6
3              22  1904     24.1    506.9   1977.6    571.0
4              22  1905      1.3    309.7   1624.9    630.8
...           ...   ...      ...      ...      ...      ...
4111           32  2011      7.9    196.2   1013.0    316.6
4112           32  2012     19.3     99.6   1119.5    167.1
4113           32  2013     60.6    131.1   1057.0    177.6
4114           32  2014     69.3     76.7    958.5    290.5
4115           32  2015      2.7    223.9    860.9    555.4

[4116 rows x 6 columns]

In [ ]:
target

0       1
1       1
2       1
3       1
4       1
       ..
4111    0
4112    0
4113    0
4114    0
4115    0
Name: ANNUAL, Length: 4116, dtype: object

# **Managing the missing data**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(features)
features1 = imputer.transform(features)

In [ ]:
features1

array([[  22. , 1901. ,  136.3,  560.3, 1696.3,  980.3],
       [  22. , 1902. ,  159.8,  458.3, 2185.9,  716.7],
       [  22. , 1903. ,  156.7,  236.1, 1874. ,  690.6],
       ...,
       [  32. , 2013. ,   60.6,  131.1, 1057. ,  177.6],
       [  32. , 2014. ,   69.3,   76.7,  958.5,  290.5],
       [  32. , 2015. ,    2.7,  223.9,  860.9,  555.4]])

In [ ]:
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
features2 = minmax.fit(features1).transform(features1)
features2

array([[0.62857143, 0.        , 0.19485347, 0.32094169, 0.36586673,
        0.78267465],
       [0.62857143, 0.00877193, 0.22844889, 0.26251575, 0.47516464,
        0.57221557],
       [0.62857143, 0.01754386, 0.22401716, 0.13523886, 0.40553633,
        0.55137725],
       ...,
       [0.91428571, 0.98245614, 0.08663331, 0.07509451, 0.22314991,
        0.14179641],
       [0.91428571, 0.99122807, 0.09907076, 0.04393401, 0.20116084,
        0.23193613],
       [0.91428571, 1.        , 0.0038599 , 0.12825066, 0.1793727 ,
        0.44343313]])

# **Encoding the independent categorical values**

In [ ]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(features))

In [ ]:
# print(X)

# **Splitting the training and testing data**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features2, target, test_size=0.1, random_state=0)

In [ ]:
X_train

array([[0.00000000e+00, 8.77192982e-02, 0.00000000e+00, 4.96620461e-02,
        5.02734680e-02, 1.76606786e-01],
       [2.85714286e-01, 7.36842105e-01, 8.46318799e-02, 4.23874442e-02,
        2.76771961e-01, 1.41237525e-01],
       [0.00000000e+00, 7.10526316e-01, 1.28663331e-03, 2.81819223e-02,
        5.13003683e-02, 2.06147705e-01],
       ...,
       [4.28571429e-01, 5.78947368e-01, 1.85704074e-01, 1.49444381e-01,
        2.09197455e-01, 1.38283433e-01],
       [7.42857143e-01, 8.77192982e-01, 8.00571837e-03, 3.57429259e-02,
        4.85612234e-01, 7.56087824e-02],
       [2.00000000e-01, 9.64912281e-01, 4.28877770e-04, 4.69698705e-03,
        1.61602857e-01, 5.01397206e-02]])

In [ ]:
X_test

array([[2.85714286e-02, 2.19298246e-01, 1.28949249e-01, 7.18868141e-02,
        5.48721956e-02, 2.36886228e-01],
       [4.85714286e-01, 5.26315789e-02, 4.22301644e-01, 1.94867682e-01,
        8.01205492e-02, 1.42115768e-02],
       [5.71428571e-01, 2.10526316e-01, 3.64546104e-02, 1.22293504e-01,
        1.76269673e-01, 1.49780439e-01],
       ...,
       [9.42857143e-01, 8.85964912e-01, 2.05861330e-02, 3.48837209e-02,
        1.88659449e-01, 4.55888224e-02],
       [8.00000000e-01, 8.85964912e-01, 3.70264475e-02, 3.72436705e-01,
        3.42091751e-01, 1.01237525e-01],
       [1.71428571e-01, 9.03508772e-01, 1.42959257e-04, 2.06381029e-01,
        5.57071102e-01, 1.25189621e-01]])

In [ ]:
y_train

3322    0
751     0
3393    0
2910    0
2196    0
       ..
1033    0
3264    0
1653    0
2607    0
2732    0
Name: ANNUAL, Length: 3704, dtype: object

In [ ]:
y_test

3452    0
1708    0
576     0
3835    0
491     1
       ..
2862    0
2948    0
883     0
308     0
3645    1
Name: ANNUAL, Length: 412, dtype: object

# **Feature Scaling**

In [ ]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(X_train)
# x_test = sc.fit_transform(X_test)

# **Model training**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
lr.score(X_test, y_test)

0.9902912621359223

# **Model Testing**

In [ ]:
def prediction(x_test, y_test):
    #learn the regressor
    #print(lr.predict(data))
    count=0
    for i in range(0, len(y_test)):
        if(lr.predict([x_test[i]])==y_test.iloc[i]):
            count+=1
    print("efficiency: "+str((count/x_test.shape[0])*100))

In [ ]:
prediction(X_test, y_test)

efficiency: 99.02912621359224
